# Absolute paths to the executables, if needed:
# ffsubsync path on Linux
ffsubsync_path=/home/abdallahxx/.local/bin/ffsubsync

# Preferred retiming tool. Allowed options: 'ffsubsync', 'alass', 'ask'.
# 1. Preferred tool for syncing to audio.
audio_subsync_tool=ffsubsync

# 2. Preferred tool for syncing to another subtitle.
altsub_subsync_tool=ffsubsync

# Unload old subs (yes,no)
# After retiming, tell mpv to forget the original subtitle track.
#unload_old_sub=yes

# Overwrite the original subtitle file.
# Replace the old subtitle file with the retimed file.
overwrite_old_sub=yes
