# Socket path (leave empty for auto)
socket=

# Thumbnail path (leave empty for auto)
thumbnail=

# Maximum thumbnail generation size in pixels
max_height=240
max_width=240

# Spawn thumbnailer on file load for faster initial thumbnails
spawn_first=yes

# Close thumbnailer process after an inactivity period in seconds
quit_after_inactivity=0

# Enable on network playback (YouTube, etc.)
network=yes

# Enable hardware decoding (Keep it 'no' for stability on Linux/Vulkan)
hwdec=no

# Custom path to the mpv executable
mpv_path=mpv
